### ISSUE TITLE
Unable to manage/edit camp statement 

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#1102]
**Steps to reproduce :**
Go to https://staging.canonizer.com/
Login with valid email and password(User A)
Create new topic and create a new camp (Camp 1)
Add camp statement
![Screenshot_2](https://user-images.githubusercontent.com/92429083/151314031-b971e4af-8d95-4832-a171-60f73c3da224.png)
Logout and login with user B
Select same topic and camp (As User A)
Click on Manage/Edit camp statement 
 I can see the note ---> No statement history available or it might be possible a user has added a statement but it's in review state
![Screenshot_1](https://user-images.githubusercontent.com/92429083/151312911-5d7df672-b9a9-4df2-88c2-491c07d413bf.png)

**Comment by aliahmad45** [comment]
Scenario 1 : 
User A creates topic ->Support will get added automatically to Agreement camp
Case 1 : When User A added camp statement to Agreement camp - It should go "live"(Grace period = 0)
Case 2 : When User B added camp statement to Agreement camp - It should go in "In Review"(Grace period = 1)

Scenario 2 : 
User A creates topic ->Create "camp 1" 
Case 1 : When User A only supported "camp 1" and also added camp statement to "camp 1" camp - It should go "live"(Grace period = 0)
Case 2 : When User A only supported "camp 1" and User B added camp statement to "camp 1" camp - It should go in "in review"(Grace period = 1)
Case 3 : When "camp 1" has no supporters and User B added camp statement to "camp 1" camp - It should go "live"(Grace period = 0)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 This is working fine now.Please verify this

**Comment by rupalichavan9860** [comment]
@Wajeeha1995 @aliahmad45 This is still not working in below scenario : 

Steps to reproduce : 
1. Go to  https://staging.canonizer.com/
2. Login with "User A" 
3. Create New topic and add camp statement for agreement camp(Note : Statement is live)
4. Logout and Login with "User B"
5. Click on "Manage/Edit Camp Statement"

Expected Result : 
User should see Camp Statement History with live record

Actual Result : 
1. It is displaying message "There is no statement history available right now. It may also be possible that a statement has been added, but it is in a review state." even if live camp statement is available


Note :  Can see Camp Statement History with live record when user not logged in

**Comment by rupalichavan9860** [comment]
Also found same issue in below scenario : 

1. Go to  https://staging.canonizer.com/
2. Login with "User A" 
3. Create New topic 
4. Logout and Login with "User B" and add camp statement for agreement camp(Note : Statement is not live)
5. Logout and Login with "User A"
6. Click on "Manage/Edit Camp Statement" and object change
7. Observe camp statement history page 

Actual Result : 
 It is displaying message "There is no statement history available right now. It may also be possible that a statement has been added, but it is in a review state." even if objected camp statement is available

![image](https://user-images.githubusercontent.com/40416610/154430784-8c6e2610-11f1-4536-8dd9-b9719a1f04b1.png)


Expected Result :
User should see Camp Statement History with objected record

**Comment by saniatg** [comment]
@aliahmad45 failing in this scenario:
Case:
Login with "User A"
Create New topic  and remove support from agreement.

Logout and Login with "User B"
Support agreement camp.
Click on "Add camp statement" and add new statement
User B will see live statement   
User A is not able to see the live statement  in 'Camp Statement History page' but  sees the statement under statement section.

**Comment by saniatg** [comment]
@aliahmad45 the above scenario is not fixed.

**Comment by ahmed130544** [comment]
Scenario 3
User A creates topic -> support will be added automatically to agreement camp
When User A remove his support and User B add support and camp statement - It should go "live"(Grace period = 0)

**Comment by saniatg** [comment]
@rupalichavan9860 the above scenario is fixed. Please confirm

**Comment by rupalichavan9860** [comment]
> Also found same issue in below scenario :
> 
> 1. Go to  https://staging.canonizer.com/
> 2. Login with "User A"
> 3. Create New topic
> 4. Logout and Login with "User B" and add camp statement for agreement camp(Note : Statement is not live)
> 5. Logout and Login with "User A"
> 6. Click on "Manage/Edit Camp Statement" and object change
> 7. Observe camp statement history page
> 
> Actual Result : It is displaying message "There is no statement history available right now. It may also be possible that a statement has been added, but it is in a review state." even if objected camp statement is available
> 
> ![image](https://user-images.githubusercontent.com/40416610/154430784-8c6e2610-11f1-4536-8dd9-b9719a1f04b1.png)
> 
> Expected Result : User should see Camp Statement History with objected record

This is not working in case of sub camp 

1. Go to  https://staging.canonizer.com/
2. Login with "User A"
3. Create New topic and create new camp "camp 1" and support "camp 1"
4. Logout and Login with "User B" and add camp statement for "camp 1" camp and commit change(Note : Statement is not live)
5. Logout and Login with "User A"
6. Click on "Manage/Edit Camp Statement" and object change
7. Observe camp statement history page

![image](https://user-images.githubusercontent.com/40416610/156315416-7f5fdaf0-6215-4deb-854e-70207e3c4c63.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 Issue is still exists. I have updated the comment with steps to reproduce .

**Comment by rupalichavan9860** [comment]
@ahmed130544 Not working in below scenario : 
1. Login with "User A"
2. Create New topic or use any existing topic and create sub camp "Camp 1" , Support "Camp 1"
3. Remove support from sub camp "Camp 1".
4. Logout and Login with "User B"
5. Support sub camp "Camp 1" .
6. Click on "Add camp statement" and add new statement
7. User B will see live statement
8. User A is not able to see the live statement on "Camp Statement History page" but sees the statement under statement section.

![image](https://user-images.githubusercontent.com/40416610/156579312-36d69f75-2322-434b-82bf-69c7ee2a451b.png)

![image](https://user-images.githubusercontent.com/40416610/156579377-edcd54a2-5049-4b5a-8c57-24d1624581dd.png)

**Comment by ahmed130544** [comment]
Scenario 4 :
User A: Created topic & camp and remove his support from camp
User B: Add support and camp statement to "camp 1" - It should go "live"(Grace period = 0)
@rupalichavan9860

**Comment by rupalichavan9860** [comment]
Tested with all possible scenarios and everything is working fine

**Comment by saniatg** [comment]
@rupalichavan9860 working on Production. Please confirm.

**Comment by rupalichavan9860** [comment]
Verified
