### ISSUE TITLE
Bad link when changing "Canonized List" back to General.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#244]
Steps to reproduce:
1. Go to https://canonizer.com
2. In the "Canonized List For" drop down, select /sandbox/
     Notice that this works, and lists the /sandbox/ topics.
3. change it back to General
    It goes to this bad URL: https://canonizer.comgeneral/

**Comment by gautamv16** [comment]
@BrentAllsop @rupalichavan9860 fixed.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and Verified.It looks good to me.
@BrentAllsop Please check and close if it is fine.

**Comment by BrentAllsop** [comment]
Brent verified this was fixed, so closing.

**Comment by rupalichavan9860** [comment]
@gautamv16 This issue is working fine on staging,but still exists on Production environment(Canonizer Main Page and Browse page)
Please refer attached screenshot for more details
Staging : 
![image](https://user-images.githubusercontent.com/40416610/45705327-ee29b780-bb96-11e8-8697-4ed74d91c1a5.png)
![image](https://user-images.githubusercontent.com/40416610/45705452-4365c900-bb97-11e8-8b35-59d64ad6ea0b.png)

Production : 
![image](https://user-images.githubusercontent.com/40416610/45705370-0ac5ef80-bb97-11e8-8332-e74c65fb3c3b.png)
![image](https://user-images.githubusercontent.com/40416610/45705478-55476c00-bb97-11e8-8ba0-39da3260d23b.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 its not an issue. You are matching the name or spelling of general but not explaining the issue if any. Its working fine, redirecting fine. Only diff is label of the general.
