### ISSUE TITLE
Change algorithm for "Mormon" canonizer.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#331]
Here is the algorithm info topic describing the current "Mormon" canonizer algorithm:

https://canonizer.com/topic/53-Mormon/6

It current has 2 parts and says:

One vote is given if you support this Mormon camp (including all supporting sub camps): 
https://canonizer.com/topic/54/7 
If you are in the camp indicating you have an LDS temple recommend, you receive an additional vote for a total of 2 votes: 
https://canonizer.com/topic/54/9 

We want to remove the second part, where people can get 2 votes for having a temple recommend.
So the description of the algorithm should only be:

One vote is given if you support this Mormon camp (including all supporting sub camps): 
https://canonizer.com/topic/54/7

This is because there are probably many Mormons that would be offended by this.

We only want to change the statement of the algorithm description camp page, once the change in the algorithm goes live.

So these 4 steps need to take place in this order:
1. Code up the algorithm change.
2. After passing testing, this will go live with a release.
3. Once it is live, change the algorithm description camp statement.
4. Close this issue.

And of course, hopefully we are working on a suite of tests that test all the canonizer algorithms.
So this will need to be updated as part of the "passing testing" step above.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by BrentAllsop** [comment]
I still see a problem.
1. Select the "Mormon" canonizer algorithm.
2. go to: https://staging.canonizer.com/topic/54-Temple-Recommend-Holder/9#statement
Before fix expected behavior: All supporters should have 2.
After fix expected behavior:  All supporters should have 1. 
This camp should be removed from adding one in the canonizer algorithm
Currently on staging I'm seeing:
![image](https://user-images.githubusercontent.com/6559312/92632806-62cbf400-f28f-11ea-992f-b08af2ad9b30.png)

And the camp score should be 4, since there should be 4 supporters with 1 point each, not the current 4.5.

**Comment by gautamv16** [comment]
@BrentAllsop I have just checked it by clicking on the link you shared above and i saw the score is 4 ie 1 for each as expected

![image](https://user-images.githubusercontent.com/6199964/93025982-1f231280-f620-11ea-8f97-7b3ca01242eb.png)


Can you please show me the use case you are getting this

**Comment by BrentAllsop** [comment]
I see what you are getting with the default algorithm, and I am seeing the problem 4.5 with the Mormon algorithm selected.

**Comment by gautamv16** [comment]
@BrentAllsop , please check i have fixed it to return score 4 only

**Comment by BrentAllsop** [comment]
Hmmm, still seeing problems:
https://staging.canonizer.com/topic/88-Theories-of-Consciousness/36-Molecular-Materialism#statement

That is my first (of many) choice, so when the Mormon canonizer (I'm a mormon) or popular consensus, it should be 0.5, but it says 1.  The total score for the camp seems correct.

**Comment by BrentAllsop** [comment]
Hmm, still seeing problems in this camp:
https://staging.canonizer.com/topic/54-Religious-Preference/10-Mormon-Transhumanist#statement
There is one Mormon supporter, but the total camp support is 2.6
And I'm the only Mormon supporting this camp (and I support more than one camp)
https://staging.canonizer.com/topic/54-Religious-Preference/16-Transhumanist
So my score should be 0.5, but it shows 1.  But that camp total correctly shows 1.

**Comment by gautamv16** [comment]
@BrentAllsop  its fixed please check.

**Comment by BrentAllsop** [comment]
Yes, I tested all this, looking great, so closing this.
Ready to put into production.
Thanks all for the quick response!!
