### ISSUE TITLE
Supported Camps page is not listing all the supported camp lists 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#586]
Please refer following scenario : 
ref topic : https://staging.canonizer.com/topic/240-Test-topic-20-dec-2019--test/1
In this topic RC supported 14 sub camps and Rupali auto has delegated their support to RC for all this 14 camps .
Now when RC try to support Agreement camp RC can see  "Warning! The following camps are child camps to "Agreement" and will be removed if you commit this support." with all 14 supported camp lists,but when Rupali auto try to support Agreement camp Rupali auto can see "Warning! The following camp are child camps to "Agreement" and will be removed if you commit this support." with only one supported camp  
I think it should display all supported camp lists.
Please confirm?
Please refer attached screenshot for more details
RC login : 
![image](https://user-images.githubusercontent.com/40416610/73295830-6f369b80-422e-11ea-85a5-3f5ee1796715.png)

Rupali auto login : 
![image](https://user-images.githubusercontent.com/40416610/73295958-b1f87380-422e-11ea-8c4e-fc43c0cae8d8.png)

**Comment by rupalichavan9860** [comment]
I found one more minor issue on this page.
when there is only one camp under supported camp list warning is displaying as "Warning! The following camp **are** child camp to "Agreement" and will be removed if you commit this support."
It should be "Warning! The following camp **is** child camp to "Agreement" and will be removed if you commit this support."
Also
"Warning! The following camp **are** parent camp to "camp 1 sub camp" and will be removed if you commit this support." should be "Warning! The following camp **is** parent camp to "camp 1 sub camp" and will be removed if you commit this support."

**Comment by BrentAllsop** [comment]
@rupalichavan9860 Oh, good catches.  Those are some complicated issues.
Lets go over some of this in our next meeting.
I'll add it to the agenda.

**Comment by BrentAllsop** [comment]
We need to make this consistent.
If you are delegating your support, and you delegate to someone else, or directly support any camp, you should get a message indicating your delegation to <delegate> will stop.
The error that shows only one delegated camp ist consistent with the fact that there are 14 camps the delegate is supporting, so this is confusing, as Rupali noticed.

**Comment by gautamv16** [comment]
@rupalichavan9860 , the issue we have found in the call is resolved. Please test and verify others as well

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.
I found some issues on supported camps pages.Please refer following scenario
Topic :  Testing 08 July 2020 test1
Testing 08 July 2020 test1 is having 5 sub camps " 1: test camp 1;2: test camp 2;3: test camp 3;4: test camp 4;5: test camp 5;" and User with nickname "RC" is supporting all 5 sub camps and User with nickname "Rupali Auto" is delegating support to RC in following 3 camps 
" 1: test camp 1;2: test camp 2;3: test camp 3"
But Support page of "Rupali auto" is displaying all 5 sub camps.Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/87246022-f2a81a00-c467-11ea-8149-cef9b75fbf87.png)

Also on user supports page list is displaying 3 times
![image](https://user-images.githubusercontent.com/40416610/87245953-6bf33d00-c467-11ea-8251-e84d3cad9085.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 . Issue is fixed. Please Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Still facing issues please refer attached screenshot
Displaying camp names 2 times also displaying non supported camp names
![image](https://user-images.githubusercontent.com/40416610/87544978-e7055f00-c6c4-11ea-9194-ffb46f0d9603.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed. Please Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working good now so closing this
