### ISSUE TITLE
Layout issue after applying as of date filter

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#710]
Issue :  User can't see As of date filter field

Select any topic and Apply as of date filter as any previous date and observe page (when screen size is 100%)
Please refer attached screenshot for more details

![image](https://user-images.githubusercontent.com/40416610/118308453-955a7a80-b509-11eb-9758-9fd1c2e018a4.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 I am not facing this issue. I have checked it in different resolution in chrome browser

**Comment by gautamv16** [comment]
@as discussed with rupli on call i found the issue and it is now fixed. @rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 I still can't see As of date filter field after applying as of date filter . Can you please check again 

![image](https://user-images.githubusercontent.com/40416610/118427170-3bfd7180-b6ea-11eb-9556-0ec874ea3338.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check again

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested on other PC and working fine for me so closing this issue
